export const mockCourseAboutResponse = {
  accessExpiration: null,
  contentTypeGatingEnabled: false,
  courseGoals: {
    selectedGoal: null,
    weeklyLearningGoalEnabled: false,
  },
  effort: null,
  end: null,
  enrollment: {
    mode: null,
    isActive: false,
  },
  enrollmentStart: null,
  enrollmentEnd: null,
  entranceExamData: {
    entranceExamCurrentScore: 0,
    entranceExamEnabled: false,
    entranceExamId: '',
    entranceExamMinimumScorePct: 0.65,
    entranceExamPassed: true,
  },
  id: 'course-v1:openedx+123+2024',
  license: null,
  language: 'en',
  media: {
    courseImage: {
      uri: '/asset-v1:openedx+123+2024+type@asset+block@494a0bae6c7f4aef47b5c0f7d85414b49371151e82646cbbbc22289b4c100c5f.jpg',
    },
    courseVideo: {
      uri: 'https://youtube.com/watch?v=test123',
    },
    image: {
      raw: 'http://local.openedx.io:8000/asset-v1:openedx+123+2024+type@asset+block@494a0bae6c7f4aef47b5c0f7d85414b49371151e82646cbbbc22289b4c100c5f.jpg',
      small: 'http://local.openedx.io:8000/asset-v1:openedx+123+2024+type@asset+block@494a0bae6c7f4aef47b5c0f7d85414b49371151e82646cbbbc22289b4c100c5f.jpg',
      large: 'http://local.openedx.io:8000/asset-v1:openedx+123+2024+type@asset+block@494a0bae6c7f4aef47b5c0f7d85414b49371151e82646cbbbc22289b4c100c5f.jpg',
    },
  },
  name: 'Test 2',
  offer: null,
  org: 'openedx',
  relatedPrograms: null,
  shortDescription: 'The first MOOC to teach positive psychology. Learn science-based principles and practices for a happy, meaningful life.',
  start: '2030-01-01T00:00:00Z',
  startDisplay: null,
  startType: 'empty',
  pacing: 'instructor',
  userTimezone: null,
  showCalculator: false,
  canAccessProctoredExams: false,
  notes: {
    enabled: false,
    visible: true,
  },
  marketingUrl: null,
  celebrations: {
    firstSection: false,
    streakLengthToCelebrate: null,
    streakDiscountEnabled: false,
    weeklyGoal: false,
  },
  userHasPassingGrade: false,
  courseExitPageIsActive: false,
  certificateData: null,
  verifyIdentityUrl: null,
  verificationStatus: 'none',
  linkedinAddToProfileUrl: null,
  isIntegritySignatureEnabled: false,
  userNeedsIntegritySignature: false,
  learningAssistantEnabled: false,
  showCoursewareLink: false,
  isCourseFull: false,
  canEnroll: true,
  invitationOnly: false,
  isShibCourse: false,
  allowAnonymous: false,
  ecommerceCheckout: false,
  singlePaidMode: {},
  ecommerceCheckoutLink: 'http://example.com/checkout',
  courseImageUrls: [
    'raw',
    'small',
    'large',
  ],
  startDateIsStillDefault: true,
  advertisedStart: null,
  coursePrice: 'Free',
  preRequisiteCourses: [],
  sidebarHtmlEnabled: false,
  courseAboutSectionHtml: null,
  aboutSidebarHtml: null,
  displayNumberWithDefault: '123',
  displayOrgWithDefault: 'openedx',
  overview: '<div>Course overview content</div>',
  ocwLinks: [],
  prerequisites: [],
};
